namespace GeradorDadosCcontabeis.dadosiniciais
{
    public class ClassificacaoItemSql : ISql
    {
        public ICollection<string> Sql { get; set; } = new List<string>
        {
            "INSERT INTO CLASSIFICACAO_ITEM (CODIGO, DESCRICAO, ATIVO) VALUES ('00', 'MERCADORIA PARA REVENDA.', TRUE);",
            "INSERT INTO CLASSIFICACAO_ITEM (CODIGO, DESCRICAO, ATIVO) VALUES ('01', 'MATÉRIA-PRIMA.', TRUE);",
            "INSERT INTO CLASSIFICACAO_ITEM (CODIGO, DESCRICAO, ATIVO) VALUES ('02', 'EMBALAGEM.', TRUE);",
            "INSERT INTO CLASSIFICACAO_ITEM (CODIGO, DESCRICAO, ATIVO) VALUES ('03', 'PRODUTO EM PROCESSO.', TRUE);",
            "INSERT INTO CLASSIFICACAO_ITEM (CODIGO, DESCRICAO, ATIVO) VALUES ('04', 'PRODUTO ACABADO.', TRUE);",
            "INSERT INTO CLASSIFICACAO_ITEM (CODIGO, DESCRICAO, ATIVO) VALUES ('05', 'SUBPRODUTO.', TRUE);",
            "INSERT INTO CLASSIFICACAO_ITEM (CODIGO, DESCRICAO, ATIVO) VALUES ('06', 'PRODUTO INTERMEDIÁRIO.', TRUE);",
            "INSERT INTO CLASSIFICACAO_ITEM (CODIGO, DESCRICAO, ATIVO) VALUES ('07', 'MATERIAL DE USO E CONSUMO.', TRUE);",
            "INSERT INTO CLASSIFICACAO_ITEM (CODIGO, DESCRICAO, ATIVO) VALUES ('08', 'ATIVO IMOBILIZADO.', TRUE);",
            "INSERT INTO CLASSIFICACAO_ITEM (CODIGO, DESCRICAO, ATIVO) VALUES ('09', 'SERVIÇOS.', TRUE);",
            "INSERT INTO CLASSIFICACAO_ITEM (CODIGO, DESCRICAO, ATIVO) VALUES ('10', 'OUTROS INSUMOS.', TRUE);",
            "INSERT INTO CLASSIFICACAO_ITEM (CODIGO, DESCRICAO, ATIVO) VALUES ('99', 'OUTRAS.', TRUE);"
        };
    }
}