namespace GeradorDadosCcontabeis.dadosiniciais
{
    public class CstsIcmsSql : ISql
    {
        public ICollection<string> Sql { get; set; } = new List<string>
        {
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (1, '00', 'TRIBUTADA INTEGRALMENTE', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (1, '10', 'TRIBUTADA E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (1, '20', 'COM REDUÇÃO DE BASE DE CÁLCULO', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (1, '30', 'ISENTA OU NÃO TRIBUTADA E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (1, '40', 'ISENTA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (1, '41', 'NÃO TRIBUTADA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (1, '50', 'COM SUSPENSÃO', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (1, '51', 'COM DIFERIMENTO', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (1, '60', 'ICMS COBRADO ANTERIORMENTE POR SUBSTITUIÇÃO TRIBUTÁRIA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (1, '70', 'COM REDUÇÃO DA BASE DE CÁLCULO E COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (1, '90', 'OUTRAS', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (2, '00', 'TRIBUTADA INTEGRALMENTE', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (2, '10', 'TRIBUTADA E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (2, '20', 'COM REDUÇÃO DE BASE DE CÁLCULO', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (2, '30', 'ISENTA OU NÃO TRIBUTADA E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (2, '40', 'ISENTA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (2, '41', 'NÃO TRIBUTADA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (2, '50', 'COM SUSPENSÃO', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (2, '51', 'COM DIFERIMENTO', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (2, '60', 'ICMS COBRADO ANTERIORMENTE POR SUBSTITUIÇÃO TRIBUTÁRIA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (2, '70', 'COM REDUÇÃO DA BASE DE CÁLCULO E COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (2, '90', 'OUTRAS', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (3, '00', 'TRIBUTADA INTEGRALMENTE', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (3, '10', 'TRIBUTADA E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (3, '20', 'COM REDUÇÃO DE BASE DE CÁLCULO', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (3, '30', 'ISENTA OU NÃO TRIBUTADA E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (3, '40', 'ISENTA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (3, '41', 'NÃO TRIBUTADA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (3, '50', 'COM SUSPENSÃO', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (3, '51', 'COM DIFERIMENTO', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (3, '60', 'ICMS COBRADO ANTERIORMENTE POR SUBSTITUIÇÃO TRIBUTÁRIA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (3, '70', 'COM REDUÇÃO DA BASE DE CÁLCULO E COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (3, '90', 'OUTRAS', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (4, '00', 'TRIBUTADA INTEGRALMENTE', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (4, '10', 'TRIBUTADA E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (4, '20', 'COM REDUÇÃO DE BASE DE CÁLCULO', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (4, '30', 'ISENTA OU NÃO TRIBUTADA E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (4, '40', 'ISENTA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (4, '41', 'NÃO TRIBUTADA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (4, '50', 'COM SUSPENSÃO', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (4, '51', 'COM DIFERIMENTO', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (4, '60', 'ICMS COBRADO ANTERIORMENTE POR SUBSTITUIÇÃO TRIBUTÁRIA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (4, '70', 'COM REDUÇÃO DA BASE DE CÁLCULO E COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (4, '90', 'OUTRAS', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (5, '00', 'TRIBUTADA INTEGRALMENTE', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (5, '10', 'TRIBUTADA E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (5, '20', 'COM REDUÇÃO DE BASE DE CÁLCULO', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (5, '30', 'ISENTA OU NÃO TRIBUTADA E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (5, '40', 'ISENTA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (5, '41', 'NÃO TRIBUTADA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (5, '50', 'COM SUSPENSÃO', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (5, '51', 'COM DIFERIMENTO', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (5, '60', 'ICMS COBRADO ANTERIORMENTE POR SUBSTITUIÇÃO TRIBUTÁRIA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (5, '70', 'COM REDUÇÃO DA BASE DE CÁLCULO E COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (5, '90', 'OUTRAS', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (6, '00', 'TRIBUTADA INTEGRALMENTE', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (6, '10', 'TRIBUTADA E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (6, '20', 'COM REDUÇÃO DE BASE DE CÁLCULO', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (6, '30', 'ISENTA OU NÃO TRIBUTADA E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (6, '40', 'ISENTA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (6, '41', 'NÃO TRIBUTADA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (6, '50', 'COM SUSPENSÃO', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (6, '51', 'COM DIFERIMENTO', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (6, '60', 'ICMS COBRADO ANTERIORMENTE POR SUBSTITUIÇÃO TRIBUTÁRIA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (6, '70', 'COM REDUÇÃO DA BASE DE CÁLCULO E COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (6, '90', 'OUTRAS', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (7, '00', 'TRIBUTADA INTEGRALMENTE', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (7, '10', 'TRIBUTADA E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (7, '20', 'COM REDUÇÃO DE BASE DE CÁLCULO', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (7, '30', 'ISENTA OU NÃO TRIBUTADA E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (7, '40', 'ISENTA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (7, '41', 'NÃO TRIBUTADA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (7, '50', 'COM SUSPENSÃO', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (7, '51', 'COM DIFERIMENTO', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (7, '60', 'ICMS COBRADO ANTERIORMENTE POR SUBSTITUIÇÃO TRIBUTÁRIA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (7, '70', 'COM REDUÇÃO DA BASE DE CÁLCULO E COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (7, '90', 'OUTRAS', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (8, '00', 'TRIBUTADA INTEGRALMENTE', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (8, '10', 'TRIBUTADA E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (8, '20', 'COM REDUÇÃO DE BASE DE CÁLCULO', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (8, '30', 'ISENTA OU NÃO TRIBUTADA E COM COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (8, '40', 'ISENTA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (8, '41', 'NÃO TRIBUTADA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (8, '50', 'COM SUSPENSÃO', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (8, '51', 'COM DIFERIMENTO', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (8, '60', 'ICMS COBRADO ANTERIORMENTE POR SUBSTITUIÇÃO TRIBUTÁRIA', false, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (8, '70', 'COM REDUÇÃO DA BASE DE CÁLCULO E COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA', TRUE, TRUE);",
            "INSERT INTO cst_icms (origem_cst, codigo, descricao, gera_base_calc, ativo) VALUES (8, '90', 'OUTRAS', TRUE, TRUE);"
        };
    }
}