namespace GeradorDadosCcontabeis.dadosiniciais
{
    public class CstsIpiSql : ISql
    {
        public ICollection<string> Sql { get; set; } = new List<string>
        {
            "INSERT INTO CST_IPI (CODIGO, DESCRICAO, APLICACAO, ATIVO) VALUES ('00', 'ENTRADA COM RECUPERAÇÃO DE CRÉDITO', 0, TRUE);",
            "INSERT INTO CST_IPI (CODIGO, DESCRICAO, APLICACAO, ATIVO) VALUES ('01', 'ENTRADA TRIBUTÁVEL COM ALÍQUOTA ZERO', 0, TRUE);",
            "INSERT INTO CST_IPI (CODIGO, DESCRICAO, APLICACAO, ATIVO) VALUES ('02', 'ENTRADA ISENTA', 0, TRUE);",
            "INSERT INTO CST_IPI (CODIGO, DESCRICAO, APLICACAO, ATIVO) VALUES ('03', 'ENTRADA NÃO-TRIBUTADA', 0, TRUE);",
            "INSERT INTO CST_IPI (CODIGO, DESCRICAO, APLICACAO, ATIVO) VALUES ('04', 'ENTRADA IMUNE', 0 , TRUE);",
            "INSERT INTO CST_IPI (CODIGO, DESCRICAO, APLICACAO, ATIVO) VALUES ('05', 'ENTRADA COM SUSPENSÃO', 0, TRUE);",
            "INSERT INTO CST_IPI (CODIGO, DESCRICAO, APLICACAO, ATIVO) VALUES ('49', 'OUTRAS ENTRADAS', 0, TRUE);",
            "INSERT INTO CST_IPI (CODIGO, DESCRICAO, APLICACAO, ATIVO) VALUES ('50', 'SAÍDA TRIBUTADA', 1, TRUE);",
            "INSERT INTO CST_IPI (CODIGO, DESCRICAO, APLICACAO, ATIVO) VALUES ('51', 'SAÍDA TRIBUTÁVEL COM ALÍQUOTA ZERO', 1, TRUE);",
            "INSERT INTO CST_IPI (CODIGO, DESCRICAO, APLICACAO, ATIVO) VALUES ('52', 'SAÍDA ISENTA', 1, TRUE);",
            "INSERT INTO CST_IPI (CODIGO, DESCRICAO, APLICACAO, ATIVO) VALUES ('53', 'SAÍDA NÃO-TRIBUTADA', 1, TRUE);",
            "INSERT INTO CST_IPI (CODIGO, DESCRICAO, APLICACAO, ATIVO) VALUES ('54', 'SAÍDA IMUNE', 1, TRUE);",
            "INSERT INTO CST_IPI (CODIGO, DESCRICAO, APLICACAO, ATIVO) VALUES ('55', 'SAÍDA COM SUSPENSÃO', 1, TRUE);",
            "INSERT INTO CST_IPI (CODIGO, DESCRICAO, APLICACAO, ATIVO) VALUES ('99', 'OUTRAS SAÍDAS', 1, TRUE);"
        };
    }
}