namespace GeradorDadosCcontabeis.dadosiniciais
{
    public class OperacoesSql : ISql
    {
        public ICollection<string> Sql { get; set; } = new List<string>
        {
            "INSERT INTO OPERACAO (ID_CFOP, CODIGO, RESULTADO_MOVIMENTO, TIPO_OPERACAO, COMISSAO_UTILIZADA, DESCRICAO, DESCRICAO_CONTABIL, PARTICIPA_SINTEGRA, PARTICIPA_SPED, PRECO_UTILIZADO, VALIDA_ESTOQUE, GERA_FINANCEIRO, SOLICITA_SENHA_ESTOQUE_NEGATIVO, SOLICITA_SENHA_LIBERACAO_CREDITO, AGRUPA_ITENS, REPROCESSA_VENCIMENTO, ATIVO) VALUES (NULL, '01', 0, 5, 2, 'CONSIGNAÇÃO', NULL, FALSE, FALSE, 4, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE);"
        };
    }
}
