namespace GeradorDadosCcontabeis.dadosiniciais
{
    public class PaisesSql : ISql
    {
        public ICollection<string> Sql { get; set; } = new List<string>
        {
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (132,'AFEGANISTAO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (175,'ALBANIA, REPUBLICA DA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (230,'ALEMANHA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (310,'BURKINA FASO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (370,'ANDORRA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (400,'ANGOLA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (418,'ANGUILLA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (434,'ANTIGUA E BARBUDA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (477,'ANTILHAS HOLANDESAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (531,'ARABIA SAUDITA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (590,'ARGELIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (639,'ARGENTINA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (647,'ARMENIA, REPUBLICA DA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (655,'ARUBA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (698,'AUSTRALIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (728,'AUSTRIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (736,'AZERBAIJAO, REPUBLICA DO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (779,'BAHAMAS, ILHAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (809,'BAHREIN, ILHAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (817,'BANGLADESH',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (833,'BARBADOS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (850,'BELARUS, REPUBLICA DA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (876,'BELGICA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (884,'BELIZE',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (906,'BERMUDAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (930,'MIANMAR (BIRMANIA)',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (973,'BOLIVIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (981,'BOSNIA-HERZEGOVINA (REPUBLICA DA)',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1015,'BOTSUANA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1058,'BRASIL',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1082,'BRUNEI',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1112,'BULGARIA, REPUBLICA DA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1155,'BURUNDI',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1198,'BUTAO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1279,'CABO VERDE, REPUBLICA DE',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1376,'CAYMAN, ILHAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1414,'CAMBOJA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1457,'CAMAROES',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1490,'CANADA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1504,'GUERNSEY, ILHA DO CANAL (INCLUI ALDERNEY E SARK)',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1508,'JERSEY, ILHA DO CANAL',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1511,'CANARIAS, ILHAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1538,'CAZAQUISTAO, REPUBLICA DO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1546,'CATAR',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1589,'CHILE',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1600,'CHINA, REPUBLICA POPULAR',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1619,'FORMOSA (TAIWAN)',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1635,'CHIPRE',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1651,'COCOS(KEELING),ILHAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1694,'COLOMBIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1732,'COMORES, ILHAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1775,'CONGO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1830,'COOK, ILHAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1872,'COREIA, REP.POP.DEMOCRATICA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1902,'COREIA, REPUBLICA DA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1937,'COSTA DO MARFIM',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1953,'CROACIA (REPUBLICA DA)',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1961,'COSTA RICA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1988,'COVEITE',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (1996,'CUBA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2291,'BENIN',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2321,'DINAMARCA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2356,'DOMINICA,ILHA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2399,'EQUADOR',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2402,'EGITO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2437,'ERITREIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2445,'EMIRADOS ARABES UNIDOS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2453,'ESPANHA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2461,'ESLOVENIA, REPUBLICA DA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2470,'ESLOVACA, REPUBLICA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2496,'ESTADOS UNIDOS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2518,'ESTONIA, REPUBLICA DA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2534,'ETIOPIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2550,'FALKLAND (ILHAS MALVINAS)',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2593,'FEROE, ILHAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2674,'FILIPINAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2712,'FINLANDIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2755,'FRANCA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2810,'GABAO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2852,'GAMBIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2895,'GANA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2917,'GEORGIA, REPUBLICA DA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2933,'GIBRALTAR',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (2976,'GRANADA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3018,'GRECIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3050,'GROENLANDIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3093,'GUADALUPE',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3131,'GUAM',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3174,'GUATEMALA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3255,'GUIANA FRANCESA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3298,'GUINE',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3310,'GUINE-EQUATORIAL',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3344,'GUINE-BISSAU',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3379,'GUIANA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3417,'HAITI',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3450,'HONDURAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3514,'HONG KONG',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3557,'HUNGRIA, REPUBLICA DA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3573,'IEMEN',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3595,'MAN, ILHA DE',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3611,'INDIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3654,'INDONESIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3697,'IRAQUE',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3727,'IRA, REPUBLICA ISLAMICA DO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3751,'IRLANDA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3794,'ISLANDIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3832,'ISRAEL',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3867,'ITALIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3913,'JAMAICA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3964,'JOHNSTON, ILHAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (3999,'JAPAO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4030,'JORDANIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4111,'KIRIBATI',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4200,'LAOS, REP.POP.DEMOCR.DO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4260,'LESOTO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4278,'LETONIA, REPUBLICA DA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4316,'LIBANO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4340,'LIBERIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4383,'LIBIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4405,'LIECHTENSTEIN',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4421,'LITUANIA, REPUBLICA DA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4456,'LUXEMBURGO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4472,'MACAU',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4499,'MACEDONIA, ANT.REP.IUGOSLAVA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4502,'MADAGASCAR',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4525,'MADEIRA, ILHA DA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4553,'MALASIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4588,'MALAVI',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4618,'MALDIVAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4642,'MALI',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4677,'MALTA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4723,'MARIANAS DO NORTE',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4740,'MARROCOS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4766,'MARSHALL,ILHAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4774,'MARTINICA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4855,'MAURICIO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4880,'MAURITANIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4901,'MIDWAY, ILHAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4936,'MEXICO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4944,'MOLDAVIA, REPUBLICA DA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4952,'MONACO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4979,'MONGOLIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4985,'MONTENEGRO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (4995,'MICRONESIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5010,'MONTSERRAT,ILHAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5053,'MOCAMBIQUE',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5070,'NAMIBIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5088,'NAURU',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5118,'CHRISTMAS,ILHA (NAVIDAD)',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5177,'NEPAL',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5215,'NICARAGUA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5258,'NIGER',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5282,'NIGERIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5312,'NIUE,ILHA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5355,'NORFOLK,ILHA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5380,'NORUEGA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5428,'NOVA CALEDONIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5452,'PAPUA NOVA GUINE',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5487,'NOVA ZELANDIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5517,'VANUATU',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5568,'OMA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5665,'PACIFICO,ILHAS DO (POSSESSAO DOS EUA)',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5738,'PAISES BAIXOS (HOLANDA)',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5754,'PALAU',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5762,'PAQUISTAO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5780,'PALESTINA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5800,'PANAMA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5860,'PARAGUAI',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5894,'PERU',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5932,'PITCAIRN,ILHA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (5991,'POLINESIA FRANCESA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6033,'POLONIA, REPUBLICA DA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6076,'PORTUGAL',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6114,'PORTO RICO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6238,'QUENIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6254,'QUIRGUIZ, REPUBLICA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6289,'REINO UNIDO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6408,'REPUBLICA CENTRO-AFRICANA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6475,'REPUBLICA DOMINICANA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6602,'REUNIAO, ILHA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6653,'ZIMBABUE',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6700,'ROMENIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6750,'RUANDA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6769,'RUSSIA, FEDERACAO DA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6777,'SALOMAO, ILHAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6781,'SAINT KITTS E NEVIS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6858,'SAARA OCIDENTAL',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6874,'EL SALVADOR',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6904,'SAMOA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6912,'SAMOA AMERICANA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6955,'SAO CRISTOVAO E NEVES,ILHAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (6971,'SAN MARINO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7005,'SAO PEDRO E MIQUELON',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7056,'SAO VICENTE E GRANADINAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7102,'SANTA HELENA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7153,'SANTA LUCIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7200,'SAO TOME E PRINCIPE, ILHAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7285,'SENEGAL',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7315,'SEYCHELLES',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7358,'SERRA LEOA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7370,'SERVIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7412,'CINGAPURA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7447,'SIRIA, REPUBLICA ARABE DA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7480,'SOMALIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7501,'SRI LANKA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7544,'SUAZILANDIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7560,'AFRICA DO SUL',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7595,'SUDAO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7600,'SUDAO DO SUL',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7641,'SUECIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7676,'SUICA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7706,'SURINAME',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7722,'TADJIQUISTAO, REPUBLICA DO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7765,'TAILANDIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7803,'TANZANIA, REP.UNIDA DA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7820,'TERRITORIO BRIT.OC.INDICO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7838,'DJIBUTI',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7889,'CHADE',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7919,'TCHECA, REPUBLICA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (7951,'TIMOR LESTE',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8001,'TOGO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8052,'TOQUELAU,ILHAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8109,'TONGA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8150,'TRINIDAD E TOBAGO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8206,'TUNISIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8230,'TURCAS E CAICOS,ILHAS',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8249,'TURCOMENISTAO, REPUBLICA DO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8273,'TURQUIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8281,'TUVALU',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8311,'UCRANIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8338,'UGANDA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8451,'URUGUAI',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8478,'UZBEQUISTAO, REPUBLICA DO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8486,'VATICANO, EST.DA CIDADE DO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8508,'VENEZUELA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8583,'VIETNA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8630,'VIRGENS,ILHAS (BRITANICAS)',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8664,'VIRGENS,ILHAS (E.U.A.)',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8702,'FIJI',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8737,'WAKE, ILHA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8885,'CONGO, REPUBLICA DEMOCRATICA DO',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8907,'ZAMBIA',true);",
            "INSERT INTO pais (codigo_ban_cen,nome,ativo)  VALUES (8958,'ZONA DO CANAL DO PANAMA',true);"
        };
    }
}
